language: android
jdk: oraclejdk11
android:
  components:
  - tools
  - tools
  - platform-tools
  - build-tools-30.0.3
  - android-30
notifications:
  email: false
before_script:
- chmod +x ./SpaceLaunchOne/gradlew
script:
- "./SpaceLaunchOne/gradlew -p ./SpaceLaunchOne assembleRelease"
- "./SpaceLaunchOne/gradlew -p ./SpaceLaunchOne javadoc"
before_install:
- openssl aes-256-cbc -K $encrypted_9b77b653ae5c_key -iv $encrypted_9b77b653ae5c_iv
  -in secrets.tar.enc -out ./SpaceLaunchOne/secrets.tar -d
- tar -C ./SpaceLaunchOne/ -xvf ./SpaceLaunchOne/secrets.tar
- yes | sdkmanager "platforms;android-30"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: javadoc
  on:
    branch: master
