language: android
dist: xenial
jdk: openjdk11
sudo: required

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-30.0.3
    - extra
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_install:
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
#  - yes | sdkmanager "build-tools;30.0.3"
  - yes | sdkmanager "platforms;android-30"
  - openssl aes-256-cbc -K $encrypted_9b77b653ae5c_key -iv $encrypted_9b77b653ae5c_iv
    -in secrets.tar.enc -out ./SpaceLaunchOne/secrets.tar -d
  - tar -C ./SpaceLaunchOne/ -xvf ./SpaceLaunchOne/secrets.tar

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_script:
  - chmod +x ./SpaceLaunchOne/gradlew

script:
  - "./SpaceLaunchOne/gradlew -p ./SpaceLaunchOne assembleRelease"
  - "./SpaceLaunchOne/gradlew -p ./SpaceLaunchOne javadoc"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  local-dir: javadoc
  on:
    branch: master
